### ISSUE TITLE
Include license in the crate source on crate.io

### ISSUE THREAD

**Issue by ghost** [rkyv/bytecheck#10]
Hi, fedora would like to have the license accessible in the crate instead of having to downloading it separately. Thanks.

**Comment by djkoloski** [comment]
One step ahead of you: 224a6bb82e80073f7cf822760fff5fb8858db349. I'll publish a minor version update with the license.

**Comment by ghost** [comment]
Thanks!

**Comment by djkoloski** [comment]
0.6.1 has been published to crates.io. I'll go update `ptr_meta`. Did you need a new rkyv version after those markdown EOL fixes?

**Comment by djkoloski** [comment]
rkyv 0.7.1 has been published with the readme fixes. Closing this issue.
