### ISSUE TITLE
ByteCheck derive macro generics issue

### ISSUE THREAD

**Issue by PonasKovas** [rkyv/bytecheck#11]
Hello, the ByteCheck derive macro doesn't work for me because it [expands to code that uses a common `'a` lifetime name (which I also use, which results in lifetime shadowing and a compile time error](https://github.com/djkoloski/bytecheck/blob/master/bytecheck_derive/src/lib.rs#L181), and also because my type has a const generic, and [the macro adds a type generic at the end of the generics, while the compiler only accepts generics in the order of lifetimes, types, generics.](https://github.com/djkoloski/bytecheck/blob/master/bytecheck_derive/src/lib.rs#L135-L137)

**Comment by djkoloski** [comment]
Fixed by 248669c17eb1a5244af1c6c3ebd3a0bbca3a896c
