### ISSUE TITLE
Re-enable simdutf8 by default

### ISSUE THREAD

**Issue by djkoloski** [rkyv/bytecheck#12]
`simdutf8` has [a mislink](https://github.com/rusticstuff/simdutf8/issues/53) on Windows with lld and thinlto. Once it's resolved, it can be re-enabled by default.

**Comment by hkratz** [comment]
This should have been fixed, see https://github.com/rust-lang/rust/issues/81408. Can you confirm?

**Comment by djkoloski** [comment]
Thanks! Fixed by 45e5d6d38be332d6e7bfac2e3cb43fc43c2dc424
