### ISSUE TITLE
Hygienics issue in derive macro

### ISSUE THREAD

**Issue by CGamesPlay** [rkyv/bytecheck#21]
Hello, I'm getting started on integrating rkyv into my crate and I ran into a small splinter. I have a custom `Result` type alias which causes errors when deriving CheckBytes. The fix is to use the fully-qualified name `::std::result::Result` everywhere in the macro.

A test case could be added that includes [no_implicit_prelude](https://doc.rust-lang.org/reference/names/preludes.html#the-no_implicit_prelude-attribute) to detect any other hygienics issues of this sort.

**Comment by djkoloski** [comment]
Fixed by f2c4eff7570aa1002793a8efd6234f98b4c6424e. I tried using `no_implicit_prelude` but it ended up causing more noise than signal by complaining about uses of `Ok`, `Err`, and `Sized`. If the opportunity comes up for a full pass on the derive macro, I'll take a look at using it then.
