### ISSUE TITLE
tests fail with Rust 1.71+

### ISSUE THREAD

**Issue by decathorpe** [rkyv/bytecheck#32]
We're packaging the bytecheck crate for Fedora Linux as a dependency of rkyv and other crates and run tests during the build. I noticed that doctests have started to fail with Rust 1.71.0 - this is also reproducible by checking out this git repo and just running "cargo test":

```
   Doc-tests bytecheck

running 1 test
test src/lib.rs - (line 23) ... FAILED

failures:

---- src/lib.rs - (line 23) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StructCheckError { field_name: "c", inner: CharCheckError { invalid_value: 51646506 } }', src/lib.rs:45:7
stack backtrace:
(actual backtrace excluded, since it's not helpful)

failures:
    src/lib.rs - (line 23)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s
```

**Comment by getong** [comment]
I delete three test code example in lib.rs, and the `cargo test` run ok, it might be the error with these three test code example.
https://github.com/rkyv/bytecheck/blob/273880316e79a0ffa3978e3bdf3708cdda1904d3/bytecheck/src/lib.rs#L57~L80
@djkoloski 
Would you take a look at it?
