### ISSUE TITLE
rkyv/0.7.44 fails with bytecheck/0.6.12 for `bytecheck::Error cannot be sent between threads safely`

### ISSUE THREAD

**Issue by mkatychev** [rkyv/bytecheck#37]
Updating to latest rkyv produces the same error addressed by https://github.com/rkyv/bytecheck/pull/27:
```
error[E0277]: `(dyn rkyv::bytecheck::Error + 'static)` cannot be sent between threads safely
   --> src/lib.rs:349:33
    |
349 |         rkyv::from_bytes(bytes).report_as()
    |                                 ^^^^^^^^^ `(dyn rkyv::bytecheck::Error + 'static)` cannot be sent between threads safely
```

I'm unable to find 0.6.12 to submit a PR, is there a commit hash I can use to do the change?

**Comment by djkoloski** [comment]
This is fixed in 0.8 (pre-released on crates.io) by providing more options for error types through rancor, and by requiring that boxed errors are `Error + Send + Sync + 'static`.
