### ISSUE TITLE
Switch string validation to `simdutf8`

### ISSUE THREAD

**Issue by djkoloski** [rkyv/bytecheck#8]
Switching string validation to [`simdutf8`](https://github.com/rusticstuff/simdutf8) should give a nice performance boost. We'll probably need to put this behind a feature (enabled by default) to allow users to choose whether they want the more portable `std` validator instead. The library does have a compatibility function, so maybe it will just switch between the two.

**Comment by hkratz** [comment]
simdutf8 falls back seamlessly to `std::str::from_utf8()` on architectures for which there is no SIMD implementation yet. On x86/x86-64 it selects the implementation at runtime. There should be no performance problems in the fallback case.

**Comment by djkoloski** [comment]
Fixed by e8ca8c8d5a158c092a264a4508848cb9d979ffa3
